#!/bin/bash
reset
UNAME=`uname -n`

cat list.txt
sleep 3
rm -f *.i *.s epd

make clean
#make SHELL='/bin/bash -x' -dn  -j1 V=1 EPD=epd7in5bV2 | egrep -v "Trying|Avoiding|Looking"
make SHELL='/bin/bash -x' -j1 V=1 EPD=epd7in5bV2 | egrep -v "Trying|Avoiding|Looking"
if [ $? != 0 ]; then
    echo "make failed"
fi

exit

set -x
if [ "$UNAME" != "whitebox" ]; then

    echo
    ask "gen SI file" 5
    ret=$?
    echo

    if [ $ret != 0 ]; then
        make clean
        genSI-fromMakefile EPD=epd7in5bV2
    fi
fi

# quickly copy to whitebox and compile and run

if [ "$UNAME" == "dwade-15R" ]; then
    xcp-whitebox /home/dwade/esp32-dev/e-paper/mfg-test.II/RaspberryPi_JetsonNano/c
    xcmd-whitebox  "set -x && cd $PWD && ./doit && file epd"
    xcmd-whitebox  "./runit $PISSWORD"
fi
